### ISSUE TITLE
Module build failed 

### ISSUE THREAD

**Issue by geekyme** [speedskater/babel-plugin-rewire#1]
Hello, I followed your instructions and added the required plugin webpack config to my karma config: 

```
// use sepia to cache outgoing HTTP requests for faster tests
// karma first run will break if there is no fixtures. run a second time to ensure passing.
// process.env.VCR_MODE = 'cache';
// require('sepia');

// Karma configuration
// Generated on Tue Apr 07 2015 17:34:20 GMT+0800 (SGT)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      // we use this pattern to load test files
      // see https://github.com/webpack/karma-webpack/issues/23
      'tests/tests_index.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
        'tests/tests_index.js': [ 'webpack', 'sourcemap' ]
    },

    webpack: { //kind of a copy of your webpack config
      devtool: 'inline-source-map', //just do inline source maps instead of the default
      module: {
        loaders: [
          { test: /\.js$/, exclude: /node_modules/, loaders: ["babel-loader?plugins=rewire"] } // loaders can take parameters as a querystring
        ]
      }
    },

    webpackServer: {
      noInfo: true //please don't spam the console when running in karma!
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // we need this proxy so that the karma server will call akamaru api which is running on localhost:5000
    proxies: {
      '/api': 'http://localhost:5000/api'
    }
  });
};
```

However, when i run ```karma start```, I am getting these errors: 

```
Module build failed: TypeError: Transformer "rewire" is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (/Users/shawnlim/Documents/react/Boa/node_modules/babel-plugin-rewire/node_modules/babel-core/lib/babel/transformation/transformer.js:118:13)
    at File.addPlugin (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/file/index.js:287:48)
    at File.buildTransformers (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/file/index.js:215:12)
    at new File (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/file/index.js:88:10)
    at Object.transform (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/index.js:43:24)
```

**Comment by speedskater** [comment]
Thanks for reporting the bug. I think this was an issue with conflicting babel versions. Therefore I switched the plugin dependency to babel core to use peer dependencies. Please update the babel-plugin-rewire to version 0.1.1 and let me know if this fixes the issue for you.

**Comment by kossnocorp** [comment]
@geekyme you have two different babel-core versions in your app, check: `npm ls babel-core`.

**Comment by citelao** [comment]
I don't think removing the dependencies fixed the issue. I get the same issue with everything up to date.

````
├─┬ babel@5.4.7 
│ └── babel-core@5.4.7 
├── babel-core@5.4.7 
├─┬ babel-loader@5.1.3
│ └── babel-core@5.4.7 
├── babel-plugin-rewire@0.1.3 
└─┬ isparta-loader@0.2.0
  └─┬ isparta@3.0.3
    └── babel-core@5.4.7 
````

**Comment by malonecj** [comment]
I'm also having the same problem. babel-loader has a local version of babel-core in its node_modules folder which I think could be causing the issue

Here are all the babel refs I have in my package.json

```
"devDependencies": {
    "babel-eslint": "^3.1.11",
    "babel-loader": "^5.1.4",
    "babel-plugin-rewire": "^0.1.3",
    "babel-runtime": "^5.5.1",
...
```

here are the different versions of babel-core when I run ```npm list babel-core```
![image](https://cloud.githubusercontent.com/assets/1432798/8005314/97ca722c-0b80-11e5-9d1a-6e7bbe62063c.png)

and here is the error. Note I'm also running this from Karma using webpack

![image](https://cloud.githubusercontent.com/assets/1432798/8005373/3c5ffd7a-0b81-11e5-994f-8eaa0673ff4d.png)

**Comment by citelao** [comment]
Any change?

**Comment by speedskater** [comment]
Might it be possible that you installed babel-core after babel-loder into your project. If you have both babel-loader as well as babel-core as a root dev dependency babel-loader will use babel-core as a peer dependenc. Hence, only one babel-core will be included.

I used the following dev dependencies:

```
"devDependencies": {
    "babel-core": "^5.5.5",
    "babel-loader": "^5.1.4"
  }
```

and  npm list resulted in the following output.

```
$ npm list babel-core
babel-plugin-rewire-issue1@1.0.0 /home/rbi/devel/babel-plugin-rewire-issue1
└── babel-core@5.5.5 
```

Maybe just delete your babel-loader folder in node-modules and reinstall it again.

**Comment by citelao** [comment]
I only get issues if I have `babel` installed— using `babel-core` generates a different error (I think on Babel's end), and using `babel-core` with `babel` generates the same error.

Don't really have time to look at this issue more atm, but your tip was helpful.

**Comment by nikolaymatrosov** [comment]
Runnig `npm dedup` has solved the issue for me.
