### ISSUE TITLE
can't run test because of version incompatibility

### ISSUE THREAD

**Issue by geekyme** [speedskater/babel-plugin-rewire#10]
Got this error:
```
Module build failed: TypeError: Transformer "rewire" is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/transformer.js:114:13)
    at PluginManager.add (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:138:55)
    at File.buildTransformers (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:287:21)
    at new File (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:150:10)
    at TransformerPipeline.transform (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
    at transpile (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/index.js:10:22)
    at Object.module.exports (/Users/shawnlim/Documents/react/Boa/node_modules/babel-loader/index.js:65:12)
```

my babel versions `npm ls babel-core`

```
├─┬ babel@5.5.6
│ └── babel-core@5.5.6
├── babel-core@5.5.6
└─┬ babel-loader@5.1.4
  └── babel-core@5.5.6
```

**Comment by geekyme** [comment]
when i uninstalled everything and reinstalled again, i get a new set of errors: 

```
Module build failed: TypeError: /Users/shawnlim/Documents/react/Boa/tests/components/pagination/pagination-prev-next.spec.js: Cannot read property 'start' of undefined
    at NodePath.errorWithNode (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/path/index.js:119:28)
    at NodePath.Scope (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/transformers/es6/constants.js:23:23)
    at NodePath.<anonymous> (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/visitors.js:190:17)
    at NodePath.call (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
    at NodePath.visit (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/path/context.js:146:8)
    at TraversalContext.visitSingle (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/context.js:105:12)
    at TraversalContext.visit (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/context.js:117:19)
    at Function.traverse.node (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at traverse (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/index.js:50:14)
    at TransformerPass.transform (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/transformer-pass.js:39:32)
 @ ./tests/components .spec\.js$
```

**Comment by geekyme** [comment]
https://github.com/babel/babel/issues/1315

**Comment by damassi** [comment]
@speedskater - this just happened to me as well.  Commenting out the plugin fixed the problem.

**Comment by speedskater** [comment]
This was an issue with renaming of variables. After using the babel scope api the issue should be fixed.
Therefore a new version containing the fix was published (0.1.4).

@damassi, @geekyme let me know if this solves your issues.

**Comment by geekyme** [comment]
it fixes this issue but created a new problem

**Comment by Rodeoclash** [comment]
Can you post more details? I'm in the process of upgrading now but haven't noticed any problems yet.

**Comment by geekyme** [comment]
https://github.com/speedskater/babel-plugin-rewire/issues/11

**Comment by speedskater** [comment]
@Rodeoclash 0.1.4 is definitively broken. I wouldn't upgrade to this version.

**Comment by speedskater** [comment]
@Rodeoclash 0.1.5 should be safe again.

**Comment by bsr203** [comment]
Hi, did the original issue solved. I get error
```
Module build failed: TypeError: Transformer "rewire" is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (/Users/bsr/schema/node_modules/babel-core/lib/babel/transformation/transformer.js:114:13)
    at PluginManager.add (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:138:55)
    at File.buildTransformers (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:287:21)
    at new File (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:150:10)
    at TransformerPipeline.transform (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
    at transpile (/usr/local/lib/node_modules/babel-loader/index.js:10:22)
```
versions

```
"babel": "^5.5.6",
    "babel-core": "^5.5.6",
    "babel-eslint": "^3.1.15",
    "babel-loader": "^5.1.4",
    "babel-plugin-rewire": "^0.1.5",

````

**Comment by damassi** [comment]
@bsr203 - delete your node modules, then reinstall all rewire related libraries.  That should fix the problem.

**Comment by bsr203** [comment]
@damassi thanks for the help. I tried everything, and seems like this is the issue.
https://github.com/babel/babel-loader/pull/58
I use webpack babel-loader :-( 

I has dependency on older version


looks like the plugin api is changed and should use `babel` directly

http://babeljs.io/docs/advanced/plugins/

**Comment by geekyme** [comment]
thanks guys can confirm that this is now working again on 0.1.5
