### ISSUE TITLE
babel 6.7 warning: You or one of the Babel plugins you are using are using Flow declarations as bindings

### ISSUE THREAD

**Issue by yvele** [speedskater/babel-plugin-rewire#108]
I'm using babel 6.6.5 (babel-core 6.7.2)

When running tests, I get a lot of those warnings in my console:

```
You or one of the Babel plugins you are using are using Flow declarations as bindings.
Support for this will be removed in version 6.8. To find out the caller, grep for this
message and change it to a `console.trace()`.
```

It looks like it's caused by this PR https://github.com/babel/babel/pull/3414

PS: babel-plugin-typecheck has the same [issue](https://github.com/codemix/babel-plugin-typecheck/issues/134)

**Comment by speedskater** [comment]
@yvele Thanks for reporting the issue I will have a look at it.

**Comment by bassettsj** [comment]
Ugh, the warning is really annoying, not your fault obviously.

What would it take to fix this soon?

**Comment by speedskater** [comment]
@bassettsj Time ;). I hope it will be fixed till the end of the week

**Comment by speedskater** [comment]
The fix is incorporated in 1.0.0-rc-2. Please let me know if this works for you.

**Comment by yvele** [comment]
@speedskater No more warnings with **1.0.0-rc-2** and everything is working.. Thanks ;)

**Comment by bassettsj** [comment]
Thanks you!

**Comment by levrik** [comment]
@speedskater I still experience this issue randomly on `1.0.0`. Babel version is `6.18.0`.

```
Trace: 
        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 6.8. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      
    at Scope.warnOnFlowBinding (C:\development\project\node_modules\babel-traverse\lib\scope\index.js:1020:15)
    at Scope.getOwnBinding (C:\development\project\node_modules\babel-traverse\lib\scope\index.js:1035:17)
    at Scope.getBinding (C:\development\project\node_modules\babel-traverse\lib\scope\index.js:1029:27)
    at getVariableNameAndBinding (C:\development\project\node_modules\babel-plugin-rewire\lib\babel-plugin-rewire.js:47:83)
    at RewireState.Identifier (C:\development\project\node_modules\babel-plugin-rewire\lib\babel-plugin-rewire.js:61:32)
    at NodePath._call (C:\development\project\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\development\project\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\development\project\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\development\project\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\development\project\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\development\project\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\development\project\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\development\project\node_modules\babel-traverse\lib\path\context.js:115:19)
    ...
```

**Comment by brendan-roche** [comment]
I'm getting this error too using babel 6.24.1.

@speedskater any chance this could be addressed, would love to use this library in our project.

**Comment by luislhl** [comment]
I'm also still getting this warning here, with version `1.1.0` and babel `6.24.1`.
Shoudn't the issue be reopened?

**Comment by jeantimex** [comment]
Same here, babel-plugin-rewire `1.1.0`, babel `6.24.1`. And here is the log:
```
at Scope.warnOnFlowBinding (node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1020:15)
at Scope.getBinding (node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1030:32)
at getVariableNameAndBinding (node_modules/babel-plugin-rewire/lib/babel-plugin-rewire.js:47:83)
at RewireState.Identifier (node_modules/babel-plugin-rewire/lib/babel-plugin-rewire.js:176:33)
at NodePath._call (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
at NodePath.visit (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
at TraversalContext.visitQueue (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
at TraversalContext.visitSingle (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
at TraversalContext.visit (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
at Function.traverse.node (node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
at NodePath.visit (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:19)
at TraversalContext.visitQueue (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
at TraversalContext.visitMultiple (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
at TraversalContext.visit (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
at Function.traverse.node (node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by AndrewSouthpaw** [comment]
Same. Please reopen.

**Comment by justinanastos** [comment]
@AndrewSouthpaw 

>Same. Please reopen, using babel-plugin-rewire 1.1.0 and babel 6.26.0. It occurs intermittently, making it even more difficult to track down. :-/

I've seen it occur intermittently only because babel cache is being used. When you disable babel cache, I believe it's 100% consistent.

**Comment by AndrewSouthpaw** [comment]
Nice, yeah just learned about the Babel cache a couple days ago, which explained the inconsistency.

Now to just figure out what's going on. 🙄
