### ISSUE TITLE
rewire is not mocking things

### ISSUE THREAD

**Issue by geekyme** [speedskater/babel-plugin-rewire#11]
Getting a whole bunch of errors now. 

```

	TypeError: intlStore.getState is not a function
	    at IntlConnection.render (/Users/shawnlim/Documents/react/Boa/tests/tests_index.js:30304:31 <- webpack:///src/utils/connect-to-intl-store.js:24:27)
```

```
Error: Store IntlStore was not registered.
	    at DispatcherContext.getStore (/Users/shawnlim/Documents/react/Boa/tests/tests_index.js:23755:20 <- webpack:///~/fluxible/~/dispatchr/lib/DispatcherContext.js:39:0)
	    at MockComponentContext.getStore (/Users/shawnlim/Documents/react/Boa/tests/tests_index.js:23958:36 <- webpack:///~/fluxible/utils/MockComponentContext.js:18:0)
```

and many more errors. 

I am simply doing this at the start of my test:

```
LoginForm.__Rewire__("FormattedMessage", React.createClass({
  render: function(){
    return <div />;
  }
}))

describe('LoginForm', function() {
  var context;
  var TestUtils;
  var MockIntlStore;
  var MockAuthStore;
  var component;
  var foundComponent;
  var LoginFormWrap;

  beforeEach(function(){

    // mock and stub out the flux's dependencies so we can test just the component's interactions
    MockIntlStore = createStore({
      storeName: 'IntlStore',
      getMessage: function(){}
    });

    MockAuthStore = createStore({
      storeName: 'AuthStore'
    });

    context = createMockComponentContext({
      stores: [MockIntlStore, MockAuthStore]
    });
```

the intlStore.getState shouldn't even be called. On 1.3 it works.

**Comment by speedskater** [comment]
You are right. Late night fixes are maybe not the best. I created a new regression. Version 0.1.3 should be okay, but 0.1.4 is definitively broken. I will try to fix it asap.

**Comment by speedskater** [comment]
there is a new version 0.1.5. It should be a workaround around the Cannot read property 'start' of undefined and reintroduce the correct behaviour.
