### ISSUE TITLE
React stateless functions fails with arrow functions

### ISSUE THREAD

**Issue by mmahalwy** [speedskater/babel-plugin-rewire#110]
Error:
```
Module build failed: TypeError: /Users/mmahalwy/Sites/sparrow/src/routes.js: Cannot read property 'node' of null
    at RewireState.JSXElement (/Users/mmahalwy/Sites/sparrow/node_modules/babel-plugin-rewire/lib/babel-plugin-rewire.js:49:47)
    at NodePath._call (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:146:16)
    at TraversalContext.visitMultiple (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:176:19)
    at Function.traverse.node (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:146:16)
    at TraversalContext.visitQueue (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:152:21)
    at TraversalContext.visitSingle (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/mmahalwy/Sites/sparrow/node_modules/babel-traverse/lib/context.js:146:16)
 @ ./src/containers/Region/spec.js 17:14-31
```
and the file is:
```
export default () => (
  <Route path="/" component={App}>
    <IndexRoute component={Home} />
  </Route>
);
```

This happens with all other stateless functions:
works:
```
const OtherRegions = () => {
  return (
  <Row>
    <Col xs={12}>
      <h2>
        <small>
          Top destinations
        </small>
      </h2>
      <ul className="list-inline">
        {
          regions.map(region => (
            <li key={region.displayGid}>
              <Link to={regionPath(region)}>
                Activities in {region.name}
              </Link>
            </li>
          ))
        }
      </ul>
    </Col>
  </Row>
);
}
```

Does not work:
```
const OtherRegions = () => (
  <Row>
    <Col xs={12}>
      <h2>
        <small>
          Top destinations
        </small>
      </h2>
      <ul className="list-inline">
        {
          regions.map(region => (
            <li key={region.displayGid}>
              <Link to={regionPath(region)}>
                Activities in {region.name}
              </Link>
            </li>
          ))
        }
      </ul>
    </Col>
  </Row>
);
```

**Comment by speedskater** [comment]
Thank you I will try to tackle it ASAP.

**Comment by mmahalwy** [comment]
@speedskater anything I can help with? This and #109 are huge blockers for me. :(

**Comment by speedskater** [comment]
@mmahalwy yes. Could you please provide a PR for #109 analogous to the valscion provided for this issue?

**Comment by mmahalwy** [comment]
@speedskater I tried to run your tests with karma and phantomjs but didn't succeed at getting it working :(

**Comment by mmahalwy** [comment]
@speedskater any luck with this?

**Comment by jmauerhan** [comment]
This is a blocker for me too :) Following to see any progress.

**Comment by speedskater** [comment]
sorry for the delay. I think I will find time this weekend to tackle this problem.

**Comment by speedskater** [comment]
The fix is incorporated in 1.0.0-rc-2. Please let me know if this works for you.

**Comment by mmahalwy** [comment]
@speedskater going to give it a try! Thanks! :tada: :tada: :tada: :tada:

**Comment by hung-phan** [comment]
Thanks for your works @speedskater. Awesome
