### ISSUE TITLE
Error on using the plugin.

### ISSUE THREAD

**Issue by nschurmann** [speedskater/babel-plugin-rewire#112]
i'm having this error, just when trying to execute an empty test with mocha:

```
TypeError: undefined is not a function
    at module.exports (/Users/nicolas/Sites/myApp/node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:26:9)
    at Function.memoisePluginContainer (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:13)
    at Function.normalisePlugin (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at /Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:30)
    at OptionManager.init (/Users/nicolas/Sites/myApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at compile (/Users/nicolas/Sites/myApp/node_modules/babel-register/lib/node.js:87:26)
    at loader (/Users/nicolas/Sites/myApp/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nicolas/Sites/myApp/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/nicolas/Sites/myApp/node_modules/mocha/lib/mocha.js:172:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/nicolas/Sites/myApp/node_modules/mocha/lib/mocha.js:169:14)
    at Mocha.run (/Users/nicolas/Sites/myApp/node_modules/mocha/lib/mocha.js:356:31)
    at loadAndRun (/Users/nicolas/Sites/myApp/node_modules/mocha/bin/_mocha:316:22)
    at Object.<anonymous> (/Users/nicolas/Sites/myApp/node_modules/mocha/bin/_mocha:333:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I'm using `npm run tdd <file>` to run my tests, when i don't configure the plugin in my `package.json` it executes the test. But i need to use this to mock a mongoose model that is imported. 

Do you know what may i be missing?
script: `"tdd": "mocha --compilers js:babel-core/register -R spec -w"`

babel config: 
```
"babel": {
    "presets": [
      "es2015"
    ],
    "plugins": ["babel-plugin-rewire"]
  }
```

**Comment by nschurmann** [comment]
What i found is that the `Plugin` method is not defined in the argument passed `pluginArguments`. Any pointers with this?

**Comment by nschurmann** [comment]
updating to `1.0.0-beta-3` solved the issue. This should be documented on the README.md
