### ISSUE TITLE
The plugin "rewire" didn't export a Plugin instance

### ISSUE THREAD

**Issue by bsr203** [speedskater/babel-plugin-rewire#21]
Hi,

I updated my babel version to latest, and getting this error.

The plugin interface was changed and can you please have a look

https://babeljs.io/docs/advanced/plugins/

```
Module build failed: TypeError: The plugin "rewire" didn't export a Plugin instance
    at PluginManager.validate (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:236:21)
    at new File (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:136:10)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/usr/local/lib/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/usr/local/lib/node_modules/babel-loader/index.js:69:12)
 @ multi main
```

versions

```
"babel": "^5.8.3",
    "babel-eslint": "^3.1.15",
    "babel-loader": "^5.3.2",
    "babel-plugin-rewire": "^0.1.11",
```

**Comment by eskimoblood** [comment]
Same here

**Comment by speedskater** [comment]
@bsr203, @eskimoblood Thanks for pointing this out. I was using the same babel versions in my tests but didn't had the same issue. 
To solve the issue I changed the plugin format in 0.1.12. Could you please try again and let me know if the fix works for you?

**Comment by bsr203** [comment]
thanks.. that fixed it!!

**Comment by jmreidy** [comment]
I'm seeing this same error with the newest versions of babel and this plugin:
```
/Users/jmreidy/Projects/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164
      throw new TypeError(messages.get("pluginNotTransformer", name));
      ^

TypeError: The plugin "rewire" didn't export a Plugin instance
```

Version numbers:
```
  "babel": "^5.8.21",
    "babel-core": "^5.8.22",
    "babel-eslint": "^4.0.10",
    "babel-loader": "^5.0.0",
    "babel-plugin-rewire": "^0.1.22",
    "babel-runtime": "^5.8.20",
```
