### ISSUE TITLE
Issue with a stray 'var' appearing in the export

### ISSUE THREAD

**Issue by girvo** [speedskater/babel-plugin-rewire#4]
Hey there,

Well done on the plugin! I've come across a bug, when wiring the plugin into Babel, then attempting to use it with my unit tests. 

The class I'm using is this one:

```
import 'isomorphic-fetch';

/**
 * Eclipse API client
 *
 * This class is the main client for the Eclipse API. It relies on environment variables (set on
 * compilation of browser code and )
 */
export default class EclipseClient
{
    constructor() {
        if (process.env.NODE_ENV !== 'production') {
            this.apiUrl = 'http:///';
        } else {
            this.apiUrl = 'http:///';
        }
    }

    // TODO: Write translation of varargs to proper body call for fetch
    async sendRequest(...args) {
        if (args.length == 0) {
            return null;
        }

        try {
            let result = await fetch(this.apiUrl, {});

            if (result.status !== 200) {
                throw new ServerException(result.status, 'Eclipse API Error!');
            }

            return await result.json();
        } catch(e) {
            throw(e);
        }
    }
}
```

And the error is as follows:

```
[08:40:16] SyntaxError in plugin 'gulp-mocha'
Message:
    /Users/josh/Work/Projects/viewfinder-1.3/code/src/shared/utils/EclipseClient.js:39
exports['default'] = Object.assign(var EclipseClient = (function () {
                                   ^^^
Unexpected token var
Stack:
/Users/josh/Work/Projects/viewfinder-1.3/code/src/shared/utils/EclipseClient.js:39
exports['default'] = Object.assign(var EclipseClient = (function () {
                                   ^^^
SyntaxError: Unexpected token var
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at normalLoader (/Users/josh/Work/Projects/viewfinder-1.3/code/node_modules/babel-core/lib/babel/api/register/node.js:147:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/josh/Work/Projects/viewfinder-1.3/code/node_modules/babel-core/lib/babel/api/register/node.js:160:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/josh/Work/Projects/viewfinder-1.3/code/tests/unit/utils/EclipseTest.js:9:36)
    at Module._compile (module.js:460:26)
```

And I've traced the error to this line in the plugin:

```
return t.exportDefaultDeclaration(t.callExpression(t.memberExpression(t.identifier('Object'),  t.identifier('assign')), [ node.declaration, t.objectExpression([
```

But I don't know enough about Babel's AST to fix it. Any ideas?

**Comment by speedskater** [comment]
Thanks for reporting the issue.
It should be fixed in version 0.1.3. Let me know if it works for you.
Furthermore in the example you provided you will have to change import 'isomorphic-fetch' to 
import fetch from 'isomorphic-fetch' to be able to mock the fetch api.
