### ISSUE TITLE
TypeError: Plugin is not a function

### ISSUE THREAD

**Issue by bomatson** [speedskater/babel-plugin-rewire#81]
I see this error when using `gulp-babel` to build:

```javascript
// gulpfile.js

gulp.task('build', function() {
  return gulp.src(src)
    .pipe(babel({
      plugins: ['rewire']
    }))
    .pipe(gulp.dest("lib"));
});
```

My `package.json`:

```json
// package.json

"dependencies": {
  // ...
  "babel": "^6.1.5",
  "babel-cli": "^6.1.4",
  "babel-preset-es2015": "^6.1.18",
  "babel-plugin-rewire": "^0.1.22",
  "gulp": "^3.9.0",
  "gulp-babel": "^6.1.0",
  // ...
}
```

Stacktrace:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Plugin is not a function
    at module.exports (/Users/bobbymatson/test/node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:26:9)
    at Function.memoisePluginContainer (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:13)
    at Function.normalisePlugin (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at /Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.init (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/bobbymatson/test/node_modules/babel-core/lib/transformation/file/index.js:121:22)
```

Looks like an issue with `pluginArguments` in `src/babel-plugin-rewire.js`. I'm assuming this is also related to changes in Babel6. 

Any thoughts on a fix? Would prefer not to downgrade, I'm also down to tackle a PR

**Comment by ssurana** [comment]
Update "babel-plugin-rewire" to "^1.0.0-beta-2"

**Comment by speedskater** [comment]
@bomatson I will close this issue, as it is invalid by using the latest beta.
