### ISSUE TITLE
Parser failing with ES6 code

### ISSUE THREAD

**Issue by balmasi** [speedskater/babel-plugin-rewire#94]
Hi,

I was trying to add rewire to my babel project by it keeps failing.

The exact procedure I followed was (babel is installed globally):

``` npm install --save-dev babel-plugin-rewire ```

running app got me:

```
module.js:327
    throw err;
    ^
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/balmasi/projects/myproject/node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:15:19)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/balmasi/projects/myproject/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

So I did `npm i -D babel-core` and tried again which got:

```
/Users/balmasi/projects/myproject/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:671
      throw err;
      ^

TypeError: /Users/balmasi/projects/myproject/server.js: Property id of FunctionDeclaration expected node to be of a type ["Identifier"] but instead got null
    at Object.validate (/Users/balmasi/projects/myproject/node_modules/babel-types/lib/definitions/index.js:101:13)
    at validate (/Users/balmasi/projects/myproject/node_modules/babel-types/lib/index.js:269:9)
    at Object.builder (/Users/balmasi/projects/myproject/node_modules/babel-types/lib/index.js:222:7)
    at accessorsFor (/Users/balmasi/projects/myproject/node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:327:26)
    at /Users/balmasi/projects/myproject/node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:251:38
    at Array.forEach (native)
    at NodePath.Plugin.visitor.ImportDeclaration (/Users/balmasi/projects/myproject/node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:233:21)
    at NodePath.call (/Users/balmasi/projects/myproject/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/balmasi/projects/myproject/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (/Users/balmasi/projects/myproject/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:108:16)
```

I'm starting my app using `nodemon --exec ./node_modules/.bin/babel-node server.js`
my **.babelrc** file looks like so:
```
{
  "stage": 0,
  "plugins": ["babel-plugin-rewire"]
}
```

and I'm making heavy use of ES6+ Features.

Any idea why this could be happening?

**Comment by speedskater** [comment]
@balmasi have your tried the latest beta?
If yes could you please provide a PR with a minimum sample causing the issue.

**Comment by balmasi** [comment]
Sure I can, but before I do, I tried it with  *^1.0.0-beta-5* and now I'm getting a new error, maybe you're familiar with this one already, if not, let me know and I'll try to reproduce a minimal sample.

```/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164
      throw new TypeError(messages.get("pluginNotTransformer", name));
            ^
TypeError: The plugin "babel-plugin-rewire" didn't export a Plugin instance
    at PluginManager.validate (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.transformFileSync (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/api/node.js:137:37)
    at compile (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:132:20)
    at normalLoader (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/balmasi/projects/project/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
```

**Comment by speedskater** [comment]
@balmasi do you have a sample code, which couses this error?

**Comment by speedskater** [comment]
I will close this bug for now. If you can provide a sample describing your error in more detail, I will reopen it.
